apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
   name: devops303
spec:
   rules:
      - host: devops303.judeaux-idryss.tk
        http:
         paths:
          - path: /
            pathType: Prefix
            backend:
              service:
               name: devops303
               port:
                number: 80
          - path: /lol
            pathType: Prefix
            backend:
              service:
               name: service-lol
               port:
                number: 80