apiVersion: v1
kind: Pod
metadata:
  name: hello-world
  labels:
    app: hello-world
    env: development
spec:
  containers:
    - name: hello-world
      image: dockercloud/hello-world
      ports:
        - containerPort: 80